<a href="https://colab.research.google.com/github/karkichtn/DATA-SCIENCE/blob/main/Lect_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

In [ ]:
a = np.array([1, 3, 9, 0, 2])
print(a)



a = np.array([1, 3, 9, 0, '2'])
print(a)

[1 3 9 0 2]
['1' '3' '9' '0' '2']


In [ ]:
# Question 2

np_arr = np.array([3,3,3,3,3.3,'hello',False])

print(bool(np_arr[-1]))

a=False
print(bool(a))

False
False


In [ ]:
a = '0'
print(bool(a))

True


In [ ]:
a = np.zeros(2)               #single array bana ne ke liye but all zeros

print(a)

[0. 0.]


In [ ]:
b = np.zeros((2,3))            #matrix or 2d array bana ne ke liye but all zeros
print(b)

In [ ]:
c = np.zeros((2,3,4))           #3d array bana ne ke liye but all zeros
print(c)

In [ ]:
a = np.ones((2,3,4),dtype=int)
print(a)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [ ]:
a = np.empty(4, dtype=int)
print(a)

[          246884115                   0 2459000718894309408
     133927700275746]


In [ ]:
a = np.full(4, 5, dtype=int)
print(a)

[5 5 5 5]


In [ ]:
a = np.arange(3, 12, 1)
b = np.linspace(3, 12, 6, dtype = int, endpoint=True)
print(b)



[ 3  4  6  8 10 12]


In [ ]:
 #Array Inspection

 #shape
 #size//  total number of element



 a = np.zeros((2,3))
 print(a.shape)

 print(a.size)



(2, 3)
6


In [ ]:
#random.randint()
#random.choice() //choice from a particular given array



a = np.random.randint(1, 7, 4)           #1 or 7 ke bich mein se random value nikalega koi bhi 4
print(a)


b = np.random.choice([2, 4, 2, 9],2)        #given array i.e 2,4,2,9 mein se koi bhi 2(jitna no. likha hain) random value dega
print(b)

[5 1 6 6]
[9 2]


In [ ]:
a = np.array([2, 3, 6])
b = np.array([4, 5 ,3])

print(a*2)
print(a+b)
print(a*b)
print(a-b)

[ 4  6 12]
[6 8 9]
[ 8 15 18]
[-2 -2  3]


In [ ]:
lst=[2,4,6,2,6,2]                # list mein opeartion perform karenge toh woh doube ho jayega
lst2=[3,2,4,6,4,2]
print(lst*2)
print(lst+lst2)

[2, 4, 6, 2, 6, 2, 2, 4, 6, 2, 6, 2]
[2, 4, 6, 2, 6, 2, 3, 2, 4, 6, 4, 2]


In [ ]:
a = np.random.randint(2, 15, 9)
print(a)
print(" ")

b = a.reshape(3, 3)
print(b)
print(" ")

# c = b.flatten()
# print(c)

c = b.transpose()
print(c)
print(" ")


d = np.concatenate(b)
print(d)
print(" ")

e = np.concatenate((b,c))
print(e)


f = np.where

[ 7  4  9 11  7  3 14 11  9]
 
[[ 7  4  9]
 [11  7  3]
 [14 11  9]]
 
[[ 7 11 14]
 [ 4  7 11]
 [ 9  3  9]]
 
[ 7  4  9 11  7  3 14 11  9]
 
[[ 7  4  9]
 [11  7  3]
 [14 11  9]
 [ 7 11 14]
 [ 4  7 11]
 [ 9  3  9]]


In [ ]:
a = np.random.randint(2,15,6)
print(a)
b= np.random.randint(1,19,6)
print(b)

print(np.concatenate((a,b)))


[7 7 7 4 2 8]
[ 2 16  7  4  3 16]
[ 7  7  7  4  2  8  2 16  7  4  3 16]


In [ ]:
a = np.random.randint(2, 15, 6)
print("a: ",a)
print(" ")

b= np.random.randint(1, 19, 6)
print("b: ",b)
print(" ")

c= np.where(b>2, b, a)                 #where vale mein condition check hogi sahi ho toh b nahi toh a
print("c: ",c)
print(" ")


d = np.sort(a)
print("d: ",d)
print(" ")

e = np.sum(a)
print("e: ",e)
print(" ")


f = np.mean(a)
print("f: ",f)
print(" ")

g = np.std(a)
print("g: ",g)
print(" ")

# h = np.var(a)
# print(h)
# print(" ")

i = np.min(a)
print("i: ",i)
print(" ")

j = np.max(a)
print("j: ",j)
print(" ")


k = np.unique(a)
print("k: ",k)
print(" ")


l = np.matmul(a, b)            #multiply kar ke plus kar de raha hain
print("l: ",l)
print(" ")



a:  [11  5  2  5  5 10]
 
b:  [ 2 18 14 18 11  8]
 
c:  [11 18 14 18 11  8]
 
d:  [ 2  5  5  5 10 11]
 
e:  38
 
f:  6.333333333333333
 
g:  3.1446603773522015
 
i:  2
 
j:  11
 
k:  [ 2  5 10 11]
 
l:  365
 


In [ ]:
# matmul()

#matrix ko multiply karta hain

a=np.random.randint(2,15,(3,3))
print(a)
print(" ")

b=np.random.randint(2,15,(3,3))
print(b)
print(" ")

c=np.matmul(a,b)
print(c)

[[12  6  9]
 [14 10 14]
 [ 9  8  6]]
 
[[ 9  4 11]
 [ 7 11  9]
 [13  6  8]]
 
[[267 168 258]
 [378 250 356]
 [215 160 219]]


In [9]:
scores = input().split()
print(scores)
scores = [int(x) for x in scores]
print(scores)

b = np.array(scores)
print(b)



1 2 3 4 5 6
['1', '2', '3', '4', '5', '6']
[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [ ]:
#Question 1


 a = np.array([3, 3, 3, 3])

 b = a
 b[0] = 1

 print(a,b)


IndentationError: unexpected indent (1269444241.py, line 4)

In [13]:
price = input().split()
print(price)
price = [int(x) for x in price]
print(price)

b = np.array(price)
print(b)

j= np.max(b)
k= np.min(b)
f= np.mean(b)
e = np.sum(b)

print("maximum price from the list is: ",j)
print("minimum price from the list is: ",k)
print("mean of the price is : ",f)
print("total price of the: ",e)



1 2 3 4 5 6
['1', '2', '3', '4', '5', '6']
[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
maximum price from the list is:  6
minimum price from the list is:  1
mean of the price is :  3.5
total price of the:  21
