<a href="https://colab.research.google.com/github/karkichtn/DATA-SCIENCE/blob/main/Lect_5(Practice_Question).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Question 1
#create a 5*5 matrix of random integer(1-90)
#find mean of values row and column wise
#replace all even number with -1
#sort the array row and column wise
#find row and coulmn wise sum saparately
#count the number of -ve's in each column



In [ ]:
import numpy as np

In [ ]:
a=np.random.randint(1,90,(5,5))
print(a)
print(" ")

#2
b=a.mean(axis=1)
print("row mean: ", b)


b=a.mean(axis=0)
print("column mean: ", b)
print(" ")



#3
# for i in range(5):
#   for j in range(5):
#     if(a[i][j]%2==0):
#       a[i][j]=-1
# print(a)

# print(" ")

# short trick
b=np.where(a%2==0,-1,a)
print(b)
print(" ")



#4 my method
# j=a.sort(axis=0)
# print(j)

#another column
j=np.sort(a,axis=0)
print("sorting: ",j)

#row wise
# j=a.sort(axis=1)
# print(j)

#another method
j=np.sort(a,axis=1)
print("sorting: ",j)

print(" ")


#5
g=a.sum(axis=0)
print(g)

g=a.sum(axis=1)
print(g)

print(" ")


#count the number of -ve's in each column

count=0
for j in range(5):
  for i in range(5):
    if(a[i][j]<0):
      count+=1
print(count)

#single line
count_col = np.sum(np.where())












[[24 78  7  9 34]
 [46 14 45 69 56]
 [89 17 31 86 88]
 [53  1  7  2 23]
 [ 4  6  5 34 77]]
 
row mean:  [30.4 46.  62.2 17.2 25.2]
column mean:  [43.2 23.2 19.  40.  55.6]
 
[[-1 -1  7  9 -1]
 [-1 -1 45 69 -1]
 [89 17 31 -1 -1]
 [53  1  7 -1 23]
 [-1 -1  5 -1 77]]
 
sorting:  [[ 4  1  5  2 23]
 [24  6  7  9 34]
 [46 14  7 34 56]
 [53 17 31 69 77]
 [89 78 45 86 88]]
sorting:  [[ 7  9 24 34 78]
 [14 45 46 56 69]
 [17 31 86 88 89]
 [ 1  2  7 23 53]
 [ 4  5  6 34 77]]
 
[216 116  95 200 278]
[152 230 311  86 126]
 
0


In [ ]:
#Question 2

#Inventory Control System

#Task:

#Create a 5x5 array (stock levels)
#Create a another 5x5 array(demand)
#Compute:
#Remaining stock = stock - demand
#Replace:
#Negative values -> 0 (out of stock)
#Find:
#Total shortage
#Product with zero stock
#Sort each row based on remaining stock

In [ ]:
a=np.random.randint(20,80,(5,5))
print("Stock: ",a)
print(" ")

b=np.random.randint(20,80,(5,5))
print("Demand: ",b)
print(" ")

remaining_stock = a-b
print("remaing stock: ",remaining_stock)
print(" ")

modified = np.where(c<0,0,c)
print("final stock: ",modified)
print(" ")

#total shortage
total_shortage = np.sum(np.where(remaining_stock < 0,remaining_stock * -1, 0))


#Product with zero stock
product_shortage= np.sum(np.where(modified==0,1,0))

print("total shortage: ",total_shortage)
print("product with zero stock: ",product_shortage)




#sort each row based on remaining stock
j=np.sort(modified,axis=1)
print("sorting: ",j)






Stock:  [[51 76 32 28 34]
 [67 65 63 54 59]
 [79 26 32 44 35]
 [78 27 34 29 20]
 [32 77 32 29 33]]
 
Demand:  [[47 24 38 37 79]
 [39 74 47 25 64]
 [77 54 33 45 69]
 [50 61 43 49 78]
 [34 45 49 44 71]]
 
remaing stock:  [[  4  52  -6  -9 -45]
 [ 28  -9  16  29  -5]
 [  2 -28  -1  -1 -34]
 [ 28 -34  -9 -20 -58]
 [ -2  32 -17 -15 -38]]
 
final stock:  [[ 0  0  0  0  0]
 [ 0  6  0  0  0]
 [49 38  0 34  0]
 [23  7  0  7  0]
 [ 0 27  0  0  0]]
 
total shortage:  331
product with zero stock:  17
sorting:  [[ 0  0  0  0  0]
 [ 0  0  0  0  6]
 [ 0  0 34 38 49]
 [ 0  0  7  7 23]
 [ 0  0  0  0 27]]
